name: Deployment

on:
  push:
    branches:
      - changes
  
permissions:
  contents: write

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: github-pages
    concurrency: production
    steps:
      - name: deploy
        run: npm run deploy "./"
      
