name: Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deployment:
    environment: github-pages
    concurrency: production
    steps:
      - name: deploy
        run: npm run deploy "./"
